CREATE DATABASE IF NOT EXISTS TestDB;
USE TestDB;

CREATE TABLE OneEntity(
  id INTEGER NOT NULL,
  someField VARCHAR,
  PRIMARY KEY (id)
);

CREATE TABLE ManyEntity(
  id INTEGER NOT NULL,
  oneConnection INTEGER,
  PRIMARY KEY (id)
);

ALTER TABLE ManyEntity ADD FOREIGN KEY (oneConnection) REFERENCES OneEntity(id);
