name:                gql2sql
version:             0.1.0.0
github:              "aaronverones/gql2sql"
license:             BSD3
author:              "Aaron Verones, Greg Gzik"
copyright:           "2019 Aaron Verones and Greg Gzik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aaronverones/gql2sql#readme>

dependencies:
- base >= 4.7 && < 5
- graphql-parser
- text
- directory

library:
  source-dirs: src

executables:
  gql2sql-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gql2sql

tests:
  gql2sql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gql2sql
